version: '3'

networks:
  laravel:

services:

  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-web
    volumes:
      - ./src/example-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: library/mysql:5.7.22
    container_name: mysql-web
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: prueba
      MYSQL_PASSWORD: prueba
      MYSQL_ROOT_PASSWORD: prueba
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - ./src/example-app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel